"""
JLPT N5 Vocabulary Word List
Total: 928 words

Sources:
  - https://github.com/elzup/jlpt-word-list (718 words, primary source)
  - https://github.com/wkei/jlpt-vocab-api (662 words)
  - https://github.com/9elt/jlpt-n5-word-list (802 words)

Each entry is a dictionary with:
  - "word": The Japanese word (kanji if applicable)
  - "reading": Hiragana reading
  - "meaning": English meaning

Note: Official JLPT vocabulary lists do not exist. These lists are
compiled from community sources based on past exam analysis.
"""


JLPT_N5_VOCAB = [
    {"word": "十", "reading": "(〜を) とお", "meaning": "ten (~)"},
    {"word": "あ", "reading": "あ", "meaning": "Ah!, Oh!"},
    {"word": "ああ", "reading": "ああ", "meaning": "Ah!, Oh!"},
    {"word": "会います", "reading": "あいます", "meaning": "see (a person), meet"},
    {"word": "会う", "reading": "あう", "meaning": "to meet, to see"},
    {"word": "青", "reading": "あお", "meaning": "blue"},
    {"word": "青い", "reading": "あおい", "meaning": "blue"},
    {"word": "赤", "reading": "あか", "meaning": "red"},
    {"word": "赤い", "reading": "あかい", "meaning": "red"},
    {"word": "明るい", "reading": "あかるい", "meaning": "bright (in reference to personality or weather); cheerful"},
    {"word": "あがります", "reading": "あがります", "meaning": "go up"},
    {"word": "秋", "reading": "あき", "meaning": "fall (season)"},
    {"word": "あきます", "reading": "あきます", "meaning": "open"},
    {"word": "開く", "reading": "あく", "meaning": "to open, to become open"},
    {"word": "開ける", "reading": "あける", "meaning": "to open (v.t.)"},
    {"word": "上げる", "reading": "あげる", "meaning": "to raise, to lift"},
    {"word": "朝", "reading": "あさ", "meaning": "morning"},
    {"word": "朝御飯", "reading": "あさごはん", "meaning": "breakfast"},
    {"word": "明後日", "reading": "あさって", "meaning": "day after tomorrow"},
    {"word": "足; 脚", "reading": "あし", "meaning": "foot; leg"},
    {"word": "明日", "reading": "あした", "meaning": "tomorrow"},
    {"word": "あそこ", "reading": "あそこ", "meaning": "there, over there, that place"},
    {"word": "あそびます", "reading": "あそびます", "meaning": "play"},
    {"word": "遊ぶ", "reading": "あそぶ", "meaning": "to play; to spend time pleasantly; to hang out"},
    {"word": "暖かい", "reading": "あたたかい", "meaning": "warm"},
    {"word": "頭", "reading": "あたま", "meaning": "head"},
    {"word": "新しい", "reading": "あたらしい", "meaning": "new"},
    {"word": "あちら", "reading": "あちら", "meaning": "this way (polite)"},
    {"word": "あっち", "reading": "あっち", "meaning": "over there"},
    {"word": "暑い", "reading": "あつい", "meaning": "hot (in reference to weather), warm"},
    {"word": "後", "reading": "あと", "meaning": "afterwards (later); in the future; the rest; since then"},
    {"word": "後(で)", "reading": "あと(で)", "meaning": "after"},
    {"word": "あなた", "reading": "あなた", "meaning": "you"},
    {"word": "兄", "reading": "あに", "meaning": "(my) older brother (humble)"},
    {"word": "姉", "reading": "あね", "meaning": "(my) older sister (humble)"},
    {"word": "あの", "reading": "あの", "meaning": "that over there; like that, that way; um..."},
    {"word": "あのう", "reading": "あのう", "meaning": "Excuse me., Well, Let me see."},
    {"word": "浴びる", "reading": "あびる", "meaning": "to bathe, to shower"},
    {"word": "危ない", "reading": "あぶない", "meaning": "dangerous, critical"},
    {"word": "甘い", "reading": "あまい", "meaning": "generous, sweet"},
    {"word": "余り", "reading": "あまり", "meaning": "not very; surplus"},
    {"word": "雨", "reading": "あめ", "meaning": "rain"},
    {"word": "あらいます", "reading": "あらいます", "meaning": "wash"},
    {"word": "洗う", "reading": "あらう", "meaning": "to wash"},
    {"word": "ありがとうございます。", "reading": "ありがとうございます。", "meaning": "Thank you very much."},
    {"word": "あります", "reading": "あります", "meaning": "be [existence]"},
    {"word": "在る", "reading": "ある", "meaning": "to be, to have"},
    {"word": "歩きます", "reading": "あるきます", "meaning": "walk"},
    {"word": "歩く", "reading": "あるく", "meaning": "to walk"},
    {"word": "あれ", "reading": "あれ", "meaning": "that one (over there)"},
    {"word": "いい", "reading": "いい", "meaning": "good [i-adj.]"},
    {"word": "いい; よい", "reading": "いい; よい", "meaning": "good"},
    {"word": "いいえ", "reading": "いいえ", "meaning": "no, not at all"},
    {"word": "いいえ。", "reading": "いいえ。", "meaning": "No"},
    {"word": "言います", "reading": "いいます", "meaning": "say, tell"},
    {"word": "言う", "reading": "いう", "meaning": "to say"},
    {"word": "家", "reading": "いえ", "meaning": "house, home"},
    {"word": "いえ。", "reading": "いえ。", "meaning": "No"},
    {"word": "いかが", "reading": "いかが", "meaning": "how, in what way"},
    {"word": "行きます", "reading": "いきます", "meaning": "go"},
    {"word": "行く", "reading": "いく", "meaning": "to go"},
    {"word": "行く", "reading": "いく; ゆく", "meaning": "to go"},
    {"word": "いくつ", "reading": "いくつ", "meaning": "how many, how old"},
    {"word": "いくら", "reading": "いくら", "meaning": "how much, how many"},
    {"word": "池", "reading": "いけ", "meaning": "pond"},
    {"word": "医者", "reading": "いしゃ", "meaning": "doctor; physician"},
    {"word": "椅子", "reading": "いす", "meaning": "chair"},
    {"word": "忙しい", "reading": "いそがしい", "meaning": "busy (people, days)"},
    {"word": "痛い", "reading": "いたい", "meaning": "hurt; painful; sore"},
    {"word": "いただきます。", "reading": "いただきます。", "meaning": "Let's eat! (saying this before having a meal.)"},
    {"word": "一", "reading": "いち", "meaning": "one"},
    {"word": "一ど", "reading": "いちど", "meaning": "once"},
    {"word": "一日", "reading": "いちにち", "meaning": "one day (duration)"},
    {"word": "一番", "reading": "いちばん", "meaning": "best (most), first, number one"},
    {"word": "一緒", "reading": "いっしょ", "meaning": "together"},
    {"word": "いっしょ(に)", "reading": "いっしょ(に)", "meaning": "together"},
    {"word": "いってきます。", "reading": "いってきます。", "meaning": "I am going., I am leaving."},
    {"word": "いつ", "reading": "いつ", "meaning": "when"},
    {"word": "五日", "reading": "いつか", "meaning": "five days; fifth day of the month"},
    {"word": "五つ", "reading": "いつつ", "meaning": "five things"},
    {"word": "いつも", "reading": "いつも", "meaning": "always, usually, every time, never (with neg. verb)"},
    {"word": "犬", "reading": "いぬ", "meaning": "dog"},
    {"word": "今", "reading": "いま", "meaning": "now"},
    {"word": "意味", "reading": "いみ", "meaning": "meaning, significance"},
    {"word": "妹", "reading": "いもうと", "meaning": "younger sister (humble)"},
    {"word": "いもうとさん", "reading": "いもうとさん", "meaning": "(someone's) younger sister"},
    {"word": "嫌", "reading": "いや", "meaning": "disagreeable, detestable, unpleasant"},
    {"word": "いらっしゃいませ。", "reading": "いらっしゃいませ。", "meaning": "May I help you? (at restaurant, shop)"},
    {"word": "入口", "reading": "いりぐち", "meaning": "entrance"},
    {"word": "いります", "reading": "いります", "meaning": "be necessary, must have, need"},
    {"word": "居る", "reading": "いる", "meaning": "(humble) to be (animate), to exist"},
    {"word": "入れる", "reading": "いれる", "meaning": "to put in"},
    {"word": "色", "reading": "いろ", "meaning": "color"},
    {"word": "色々", "reading": "いろいろ", "meaning": "various"},
    {"word": "上", "reading": "うえ", "meaning": "above (up, top, etc.), over, on top of"},
    {"word": "後ろ", "reading": "うしろ", "meaning": "back, behind, rear"},
    {"word": "薄い", "reading": "うすい", "meaning": "thin, weak"},
    {"word": "歌", "reading": "うた", "meaning": "a song"},
    {"word": "うたいます", "reading": "うたいます", "meaning": "sing"},
    {"word": "歌う", "reading": "うたう", "meaning": "to sing"},
    {"word": "うち", "reading": "うち", "meaning": "home; house; my place"},
    {"word": "生まれる", "reading": "うまれる", "meaning": "to be born"},
    {"word": "海", "reading": "うみ", "meaning": "sea, beach"},
    {"word": "うります", "reading": "うります", "meaning": "sell"},
    {"word": "売る", "reading": "うる", "meaning": "to sell (v.t.)"},
    {"word": "うるさい", "reading": "うるさい", "meaning": "noisy; annoying"},
    {"word": "うれしい", "reading": "うれしい", "meaning": "happy, pleased [i-adj.]"},
    {"word": "上着", "reading": "うわぎ", "meaning": "coat, jacket"},
    {"word": "うーん", "reading": "うーん", "meaning": "Well, Let me see."},
    {"word": "絵", "reading": "え", "meaning": "a painting; a picture; a drawing"},
    {"word": "映画", "reading": "えいが", "meaning": "movie, film"},
    {"word": "映画館", "reading": "えいがかん", "meaning": "movie theater, cinema"},
    {"word": "英語", "reading": "えいご", "meaning": "English (language)"},
    {"word": "ええ", "reading": "ええ", "meaning": "yes"},
    {"word": "駅", "reading": "えき", "meaning": "station"},
    {"word": "えっ", "reading": "えっ", "meaning": "Oh! = え。"},
    {"word": "えらびます", "reading": "えらびます", "meaning": "choose"},
    {"word": "鉛筆", "reading": "えんぴつ", "meaning": "pencil"},
    {"word": "えー", "reading": "えー", "meaning": "Well, Let me see."},
    {"word": "美味しい", "reading": "おいしい", "meaning": "delicious, tasty"},
    {"word": "おいでになります", "reading": "おいでになります", "meaning": "come, go, be [respect]"},
    {"word": "多い", "reading": "おおい", "meaning": "many; there are a lot"},
    {"word": "大きい", "reading": "おおきい", "meaning": "big, large"},
    {"word": "大きな", "reading": "おおきな", "meaning": "big"},
    {"word": "大勢", "reading": "おおぜい", "meaning": "great number of people"},
    {"word": "お母さん", "reading": "おかあさん", "meaning": "mother (formal)"},
    {"word": "お菓子", "reading": "おかし", "meaning": "confections, sweets, snack"},
    {"word": "お金", "reading": "おかね", "meaning": "money"},
    {"word": "起きる", "reading": "おきる", "meaning": "to get up (e.g., from sleeping); to happen"},
    {"word": "置く", "reading": "おく", "meaning": "to put; to lay; to place"},
    {"word": "奥さん", "reading": "おくさん", "meaning": "(someone else's) wife (hon.)"},
    {"word": "お国", "reading": "おくに", "meaning": "country = くに。"},
    {"word": "おくります", "reading": "おくります", "meaning": "send"},
    {"word": "おげんきで。", "reading": "おげんきで。", "meaning": "Take care of yourself."},
    {"word": "お酒", "reading": "おさけ", "meaning": "sake; alcohol"},
    {"word": "お皿", "reading": "おさら", "meaning": "plate, dish"},
    {"word": "教える", "reading": "おしえる", "meaning": "to teach, to inform, to instruct"},
    {"word": "おじいさん", "reading": "おじいさん", "meaning": "grandfather, male senior citizen"},
    {"word": "伯父; 叔父さん", "reading": "おじさん", "meaning": "uncle, middle-aged man"},
    {"word": "押す", "reading": "おす", "meaning": "to push, to press, to stamp (e.g., a passport)"},
    {"word": "遅い", "reading": "おそい", "meaning": "slow; (to be) late"},
    {"word": "おそく", "reading": "おそく", "meaning": "late [noun]"},
    {"word": "お茶", "reading": "おちゃ", "meaning": "(green) tea"},
    {"word": "お手洗い", "reading": "おてあらい", "meaning": "toilet, restroom, bathroom (lit., a place to wash one's hands)"},
    {"word": "お父さん", "reading": "おとうさん", "meaning": "father (formal)"},
    {"word": "弟", "reading": "おとうと", "meaning": "younger brother"},
    {"word": "おとうとさん", "reading": "おとうとさん", "meaning": "(someone's) younger brother"},
    {"word": "男", "reading": "おとこ", "meaning": "man, male"},
    {"word": "男の子", "reading": "おとこのこ", "meaning": "boy"},
    {"word": "一昨日", "reading": "おととい", "meaning": "the day before yesterday"},
    {"word": "おととし", "reading": "おととし", "meaning": "year before last"},
    {"word": "大人", "reading": "おとな", "meaning": "adult"},
    {"word": "お腹", "reading": "おなか", "meaning": "stomach"},
    {"word": "同じ", "reading": "おなじ", "meaning": "same, identical"},
    {"word": "お兄さん", "reading": "おにいさん", "meaning": "(someone else's) older brother (formal)"},
    {"word": "おにぎり", "reading": "おにぎり", "meaning": "rice ball"},
    {"word": "お姉さん", "reading": "おねえさん", "meaning": "older sister (formal)"},
    {"word": "おねがいします。", "reading": "おねがいします。", "meaning": "Please."},
    {"word": "おはようございます。", "reading": "おはようございます。", "meaning": "Good morning."},
    {"word": "おばあさん", "reading": "おばあさん", "meaning": "grandmother, female senior-citizen"},
    {"word": "伯母さん; 叔母さん", "reading": "おばさん", "meaning": "aunt"},
    {"word": "お風呂", "reading": "おふろ", "meaning": "a bath"},
    {"word": "お弁当", "reading": "おべんとう", "meaning": "a boxed lunch"},
    {"word": "覚える", "reading": "おぼえる", "meaning": "to learn, to commit to memory, to remember, to memorize"},
    {"word": "おまわりさん", "reading": "おまわりさん", "meaning": "policeman (friendly term)"},
    {"word": "お店", "reading": "おみせ", "meaning": "shop = みせ。"},
    {"word": "重い", "reading": "おもい", "meaning": "heavy; serious"},
    {"word": "面白い", "reading": "おもしろい", "meaning": "interesting, amusing"},
    {"word": "おやすみなさい。", "reading": "おやすみなさい。", "meaning": "Good night."},
    {"word": "およぎます", "reading": "およぎます", "meaning": "swim"},
    {"word": "泳ぐ", "reading": "およぐ", "meaning": "to swim"},
    {"word": "降りる", "reading": "おりる", "meaning": "to get off"},
    {"word": "おわります", "reading": "おわります", "meaning": "end, finish"},
    {"word": "終る", "reading": "おわる", "meaning": "to finish, to close"},
    {"word": "音楽", "reading": "おんがく", "meaning": "Music"},
    {"word": "女", "reading": "おんな", "meaning": "woman, female"},
    {"word": "女の子", "reading": "おんなのこ", "meaning": "girl"},
    {"word": "お～", "reading": "お～", "meaning": "honorable ~ (honorific)"},
    {"word": "火", "reading": "か", "meaning": "Tuesday = かようび。"},
    {"word": "会社", "reading": "かいしゃ", "meaning": "company, corporation"},
    {"word": "階段", "reading": "かいだん", "meaning": "stairs"},
    {"word": "かいとうようし", "reading": "かいとうようし", "meaning": "answer sheet"},
    {"word": "買います", "reading": "かいます", "meaning": "buy"},
    {"word": "買い物", "reading": "かいもの", "meaning": "shopping"},
    {"word": "買う", "reading": "かう", "meaning": "to buy"},
    {"word": "かえします", "reading": "かえします", "meaning": "return (object)"},
    {"word": "返す", "reading": "かえす", "meaning": "to return something"},
    {"word": "かえります", "reading": "かえります", "meaning": "return, go back"},
    {"word": "帰る", "reading": "かえる", "meaning": "to go back, to go home, to return"},
    {"word": "顔", "reading": "かお", "meaning": "face (body part)"},
    {"word": "かかります", "reading": "かかります", "meaning": "take (time, money)"},
    {"word": "かかる", "reading": "かかる", "meaning": "it takes (amount of time, money) (v.i.)"},
    {"word": "書きます", "reading": "かきます", "meaning": "write"},
    {"word": "鍵", "reading": "かぎ", "meaning": "a lock; a key"},
    {"word": "書く", "reading": "かく", "meaning": "to write"},
    {"word": "掛ける", "reading": "かける", "meaning": "to put on (e.g., glasses); to hang (e.g., on a wall)"},
    {"word": "傘", "reading": "かさ", "meaning": "umbrella, parasol"},
    {"word": "かします", "reading": "かします", "meaning": "lend"},
    {"word": "貸す", "reading": "かす", "meaning": "to lend"},
    {"word": "風", "reading": "かぜ", "meaning": "wind, breeze"},
    {"word": "家族", "reading": "かぞく", "meaning": "family, members of a family"},
    {"word": "方", "reading": "かた", "meaning": "-- honorific form for 人 (ひと) --; way of doing"},
    {"word": "片仮名", "reading": "かたかな", "meaning": "katakana"},
    {"word": "家庭", "reading": "かてい", "meaning": "home; family"},
    {"word": "角", "reading": "かど", "meaning": "corner (e.g., desk, pavement)"},
    {"word": "かない", "reading": "かない", "meaning": "(my) wife"},
    {"word": "かばん", "reading": "かばん", "meaning": "bag, basket"},
    {"word": "花瓶", "reading": "かびん", "meaning": "(flower) vase"},
    {"word": "かぶります", "reading": "かぶります", "meaning": "put on"},
    {"word": "かぶる", "reading": "かぶる", "meaning": "to wear, to put on (e.g., a hat on the head)"},
    {"word": "紙", "reading": "かみ", "meaning": "paper"},
    {"word": "火曜日", "reading": "かようび", "meaning": "Tuesday"},
    {"word": "辛い", "reading": "からい", "meaning": "hot and spicy; salty"},
    {"word": "体", "reading": "からだ", "meaning": "body; health"},
    {"word": "借りる", "reading": "かりる", "meaning": "to borrow, to owe"},
    {"word": "軽い", "reading": "かるい", "meaning": "light, non-serious, minor"},
    {"word": "川; 河", "reading": "かわ", "meaning": "river"},
    {"word": "可愛い", "reading": "かわいい", "meaning": "cute, adorable"},
    {"word": "かんがえます", "reading": "かんがえます", "meaning": "consider, think"},
    {"word": "漢字", "reading": "かんじ", "meaning": "kanji; Chinese character"},
    {"word": "かんたん", "reading": "かんたん", "meaning": "easy [na-adj.]"},
    {"word": "外国", "reading": "がいこく", "meaning": "foreign country; abroad"},
    {"word": "外国人", "reading": "がいこくじん", "meaning": "foreigner"},
    {"word": "学生", "reading": "がくせい", "meaning": "student"},
    {"word": "学校", "reading": "がっこう", "meaning": "a school"},
    {"word": "木", "reading": "き", "meaning": "tree, wood, timber"},
    {"word": "黄色", "reading": "きいろ", "meaning": "yellow"},
    {"word": "黄色い", "reading": "きいろい", "meaning": "yellow"},
    {"word": "消える", "reading": "きえる", "meaning": "to vanish, to disappear"},
    {"word": "聞きます", "reading": "ききます", "meaning": "ask, hear, listen"},
    {"word": "聞く", "reading": "きく", "meaning": "to hear, to listen, to ask"},
    {"word": "北", "reading": "きた", "meaning": "north"},
    {"word": "汚い", "reading": "きたない", "meaning": "dirty, unclean, filthy"},
    {"word": "喫茶店", "reading": "きっさてん", "meaning": "café"},
    {"word": "切手", "reading": "きって", "meaning": "postal (postage) stamps"},
    {"word": "切符", "reading": "きっぷ", "meaning": "a ticket"},
    {"word": "昨日", "reading": "きのう", "meaning": "yesterday"},
    {"word": "九", "reading": "きゅう", "meaning": "nine"},
    {"word": "九", "reading": "きゅう / く", "meaning": "nine"},
    {"word": "今日", "reading": "きょう", "meaning": "today, this day"},
    {"word": "教室", "reading": "きょうしつ", "meaning": "classroom"},
    {"word": "兄弟", "reading": "きょうだい", "meaning": "siblings (humble), brothers and sisters"},
    {"word": "きょうと", "reading": "きょうと", "meaning": "Kyoto [name of city]"},
    {"word": "去年", "reading": "きょねん", "meaning": "last year"},
    {"word": "嫌い", "reading": "きらい", "meaning": "dislike"},
    {"word": "きります", "reading": "きります", "meaning": "cut"},
    {"word": "切る", "reading": "きる", "meaning": "to cut; to hang up (a phone)"},
    {"word": "綺麗", "reading": "きれい", "meaning": "pretty, clean, tidy"},
    {"word": "金", "reading": "きん", "meaning": "Friday = きんようび。"},
    {"word": "金曜日", "reading": "きんようび", "meaning": "Friday"},
    {"word": "牛肉", "reading": "ぎゅうにく", "meaning": "beef"},
    {"word": "牛乳", "reading": "ぎゅうにゅう", "meaning": "milk"},
    {"word": "銀行", "reading": "ぎんこう", "meaning": "bank"},
    {"word": "九", "reading": "く", "meaning": "nine"},
    {"word": "薬", "reading": "くすり", "meaning": "medicine"},
    {"word": "下さい", "reading": "ください", "meaning": "(with te-form verb) please do for me"},
    {"word": "ください。", "reading": "ください。", "meaning": "Please give me."},
    {"word": "果物", "reading": "くだもの", "meaning": "fruit"},
    {"word": "口", "reading": "くち", "meaning": "job opening; mouth"},
    {"word": "靴", "reading": "くつ", "meaning": "shoes, footwear"},
    {"word": "靴下", "reading": "くつした", "meaning": "socks"},
    {"word": "国", "reading": "くに", "meaning": "country; place of origin"},
    {"word": "曇り", "reading": "くもり", "meaning": "cloudiness, cloudy weather"},
    {"word": "曇る", "reading": "くもる", "meaning": "to become cloudy, to become dim"},
    {"word": "暗い", "reading": "くらい", "meaning": "dark, gloomy"},
    {"word": "来る", "reading": "くる", "meaning": "to come"},
    {"word": "車", "reading": "くるま", "meaning": "car, vehicle"},
    {"word": "黒", "reading": "くろ", "meaning": "black"},
    {"word": "黒い", "reading": "くろい", "meaning": "black; dark"},
    {"word": "くろく", "reading": "くろく", "meaning": "black [adv.]"},
    {"word": "警官", "reading": "けいかん", "meaning": "police officer"},
    {"word": "今朝", "reading": "けさ", "meaning": "this morning"},
    {"word": "けします", "reading": "けします", "meaning": "switch off, turn off, erase"},
    {"word": "けしゴム", "reading": "けしゴム", "meaning": "eraser"},
    {"word": "消す", "reading": "けす", "meaning": "to erase, to delete, to turn off power"},
    {"word": "結構", "reading": "けっこう", "meaning": "splendid; enough, tolerably"},
    {"word": "結婚", "reading": "けっこん", "meaning": "marriage"},
    {"word": "結婚", "reading": "けっこん (する)", "meaning": "marriage (get married)"},
    {"word": "けっこんします", "reading": "けっこんします", "meaning": "get married"},
    {"word": "月", "reading": "げつ", "meaning": "Monday = げつようび。"},
    {"word": "月曜日", "reading": "げつようび", "meaning": "Monday"},
    {"word": "玄関", "reading": "げんかん", "meaning": "entrance (to a house or a building)"},
    {"word": "元気", "reading": "げんき", "meaning": "health(y), energetic"},
    {"word": "公園", "reading": "こうえん", "meaning": "a park"},
    {"word": "交差点", "reading": "こうさてん", "meaning": "intersection"},
    {"word": "紅茶", "reading": "こうちゃ", "meaning": "black tea"},
    {"word": "交番", "reading": "こうばん", "meaning": "police box"},
    {"word": "声", "reading": "こえ", "meaning": "voice"},
    {"word": "ここ", "reading": "ここ", "meaning": "here, this place"},
    {"word": "九日", "reading": "ここのか", "meaning": "nine days; ninth day of the month"},
    {"word": "九つ", "reading": "ここのつ", "meaning": "nine things"},
    {"word": "こたえ", "reading": "こたえ", "meaning": "answer"},
    {"word": "こたえかた", "reading": "こたえかた", "meaning": "how to answer"},
    {"word": "答える", "reading": "こたえる", "meaning": "to answer, to reply"},
    {"word": "こちら", "reading": "こちら", "meaning": "this person (polite); this way (polite)"},
    {"word": "こちらこそ。", "reading": "こちらこそ。", "meaning": "It is me, not you that ..."},
    {"word": "こっち", "reading": "こっち", "meaning": "this person; this direction; this side"},
    {"word": "今年", "reading": "ことし", "meaning": "this year"},
    {"word": "言葉", "reading": "ことば", "meaning": "language; word(s); expression(s)"},
    {"word": "子供", "reading": "こども", "meaning": "child(ren)"},
    {"word": "この", "reading": "この", "meaning": "this"},
    {"word": "こまります", "reading": "こまります", "meaning": "be in trouble"},
    {"word": "困る", "reading": "こまる", "meaning": "to be bothered, to have difficulty"},
    {"word": "これ", "reading": "これ", "meaning": "this one"},
    {"word": "今月", "reading": "こんげつ", "meaning": "this month"},
    {"word": "今週", "reading": "こんしゅう", "meaning": "this week"},
    {"word": "こんな", "reading": "こんな", "meaning": "such, like this"},
    {"word": "こんにちは。", "reading": "こんにちは。", "meaning": "Good morning., Good afternoon., Hello."},
    {"word": "今晩", "reading": "こんばん", "meaning": "tonight, this evening"},
    {"word": "こんばんは。", "reading": "こんばんは。", "meaning": "Good evening."},
    {"word": "五", "reading": "ご", "meaning": "five"},
    {"word": "午後", "reading": "ごご", "meaning": "afternoon, P.M."},
    {"word": "ごしゅじん", "reading": "ごしゅじん", "meaning": "(someone's) husband"},
    {"word": "午前", "reading": "ごぜん", "meaning": "morning, A.M."},
    {"word": "ごちそうさまでした。", "reading": "ごちそうさまでした。", "meaning": "I've enjoyed my meal very much. Thank you. (saying this after having a meal.)"},
    {"word": "御飯", "reading": "ごはん", "meaning": "rice (cooked); meal"},
    {"word": "ごめんください。", "reading": "ごめんください。", "meaning": "Hello!, May I come in?"},
    {"word": "ごめんなさい。", "reading": "ごめんなさい。", "meaning": "Sorry."},
    {"word": "さあ", "reading": "さあ", "meaning": "come now, well"},
    {"word": "さあ…", "reading": "さあ…", "meaning": "Well ..."},
    {"word": "さいご", "reading": "さいご", "meaning": "end, last time"},
    {"word": "財布", "reading": "さいふ", "meaning": "wallet"},
    {"word": "魚", "reading": "さかな", "meaning": "fish"},
    {"word": "先", "reading": "さき", "meaning": "future; recent, previous"},
    {"word": "さきます", "reading": "さきます", "meaning": "bloom"},
    {"word": "咲く", "reading": "さく", "meaning": "to bloom"},
    {"word": "作文", "reading": "さくぶん", "meaning": "essay; composition"},
    {"word": "さします", "reading": "さします", "meaning": "put up (umbrella)"},
    {"word": "差す", "reading": "さす", "meaning": "to raise (stretch out) hands, to raise (e.g., umbrella)"},
    {"word": "砂糖", "reading": "さとう", "meaning": "sugar"},
    {"word": "寒い", "reading": "さむい", "meaning": "cold (in reference to weather)"},
    {"word": "さようなら。", "reading": "さようなら。", "meaning": "Goodbye."},
    {"word": "さ来年", "reading": "さらいねん", "meaning": "year after next"},
    {"word": "さんぽ", "reading": "さんぽ", "meaning": "walk"},
    {"word": "散歩", "reading": "さんぽ (する)", "meaning": "walk, stroll"},
    {"word": "さんぽ(を)します", "reading": "さんぽ(を)します", "meaning": "take a walk"},
    {"word": "雑誌", "reading": "ざっし", "meaning": "magazine, journal"},
    {"word": "四", "reading": "し", "meaning": "four"},
    {"word": "四", "reading": "し / よん", "meaning": "four"},
    {"word": "塩", "reading": "しお", "meaning": "salt"},
    {"word": "しかし", "reading": "しかし", "meaning": "however; but"},
    {"word": "仕事", "reading": "しごと", "meaning": "work, job, occupation, employment"},
    {"word": "静か", "reading": "しずか", "meaning": "quiet, calm"},
    {"word": "下", "reading": "した", "meaning": "under, below, beneath"},
    {"word": "七", "reading": "しち", "meaning": "seven"},
    {"word": "七", "reading": "しち / なな", "meaning": "seven"},
    {"word": "質問", "reading": "しつもん", "meaning": "question, inquiry"},
    {"word": "しつれいしました。", "reading": "しつれいしました。", "meaning": "I am sorry. (I am sorry to have been rude.)"},
    {"word": "しつれいします。", "reading": "しつれいします。", "meaning": "Excuse me."},
    {"word": "しにます", "reading": "しにます", "meaning": "die"},
    {"word": "死ぬ", "reading": "しぬ", "meaning": "to die"},
    {"word": "しまります", "reading": "しまります", "meaning": "close (intransitive verb)"},
    {"word": "閉まる", "reading": "しまる", "meaning": "to close, to be closed"},
    {"word": "閉める", "reading": "しめる", "meaning": "to close, to shut"},
    {"word": "写真", "reading": "しゃしん", "meaning": "a picture; a photograph"},
    {"word": "週", "reading": "しゅう", "meaning": "week"},
    {"word": "宿題", "reading": "しゅくだい", "meaning": "homework"},
    {"word": "醤油", "reading": "しょうゆ", "meaning": "soy sauce"},
    {"word": "食堂", "reading": "しょくどう", "meaning": "cafeteria, dining hall"},
    {"word": "知る", "reading": "しる", "meaning": "to know, to understand"},
    {"word": "白", "reading": "しろ", "meaning": "white"},
    {"word": "白い", "reading": "しろい", "meaning": "white"},
    {"word": "新聞", "reading": "しんぶん", "meaning": "newspaper"},
    {"word": "時間", "reading": "じかん", "meaning": "time"},
    {"word": "辞書", "reading": "じしょ", "meaning": "dictionary"},
    {"word": "自転車", "reading": "じてんしゃ", "meaning": "bicycle"},
    {"word": "自動車", "reading": "じどうしゃ", "meaning": "automobile"},
    {"word": "字引", "reading": "じびき", "meaning": "dictionary"},
    {"word": "自分", "reading": "じぶん", "meaning": "myself, oneself"},
    {"word": "じゃ", "reading": "じゃ", "meaning": "then, well, well then, if so, in the case."},
    {"word": "じゃ; じゃあ", "reading": "じゃ; じゃあ", "meaning": "well, well then"},
    {"word": "じゃあ", "reading": "じゃあ", "meaning": "then, well, well then, if so, in the case."},
    {"word": "十", "reading": "じゅう", "meaning": "ten"},
    {"word": "十", "reading": "じゅう  とお", "meaning": "ten"},
    {"word": "授業", "reading": "じゅぎょう", "meaning": "a class (of school)"},
    {"word": "上手", "reading": "じょうず", "meaning": "be good at, skillful"},
    {"word": "上手に", "reading": "じょうずに", "meaning": "well [adv.]"},
    {"word": "丈夫", "reading": "じょうぶ", "meaning": "strong, solid, durable"},
    {"word": "水", "reading": "すい", "meaning": "Wednesday = すいようび。"},
    {"word": "すいます", "reading": "すいます", "meaning": "breath in, smoke"},
    {"word": "水曜日", "reading": "すいようび", "meaning": "Wednesday"},
    {"word": "吸う", "reading": "すう", "meaning": "to breathe in, to suck"},
    {"word": "好き", "reading": "すき", "meaning": "liking, fondness, love"},
    {"word": "少ない", "reading": "すくない", "meaning": "a little; a few"},
    {"word": "すぐに", "reading": "すぐに", "meaning": "immediately, soon"},
    {"word": "少し", "reading": "すこし", "meaning": "little, few"},
    {"word": "すし", "reading": "すし", "meaning": "sushi"},
    {"word": "すしや", "reading": "すしや", "meaning": "sushi restaurant"},
    {"word": "涼しい", "reading": "すずしい", "meaning": "cool, refreshing (in reference to weather)"},
    {"word": "住みます", "reading": "すみます", "meaning": "live, inhabit"},
    {"word": "すみません。", "reading": "すみません。", "meaning": "Excuse me."},
    {"word": "住む", "reading": "すむ", "meaning": "to reside, to live in"},
    {"word": "する", "reading": "する", "meaning": "to do, to try; to wear small items (e.g., necktie, watch, etc.)"},
    {"word": "すわります", "reading": "すわります", "meaning": "sit down"},
    {"word": "座る", "reading": "すわる", "meaning": "to sit"},
    {"word": "背", "reading": "せ", "meaning": "height, stature"},
    {"word": "背", "reading": "せい", "meaning": "(one's) height, stature"},
    {"word": "生徒", "reading": "せいと", "meaning": "student; pupil"},
    {"word": "石鹸", "reading": "せっけん", "meaning": "soap"},
    {"word": "背広", "reading": "せびろ", "meaning": "men's suit"},
    {"word": "狭い", "reading": "せまい", "meaning": "narrow; not spacious"},
    {"word": "千", "reading": "せん", "meaning": "thousand"},
    {"word": "先月", "reading": "せんげつ", "meaning": "last month"},
    {"word": "先週", "reading": "せんしゅう", "meaning": "last week"},
    {"word": "先生", "reading": "せんせい", "meaning": "teacher, professor; master; doctor"},
    {"word": "洗濯", "reading": "せんたく", "meaning": "washing, laundry"},
    {"word": "全部", "reading": "ぜんぶ", "meaning": "all, entire, whole"},
    {"word": "そう; そうです", "reading": "そう; そうです", "meaning": "yes; appears, to be the case"},
    {"word": "そうして; そして", "reading": "そうして; そして", "meaning": "and, like that"},
    {"word": "そうしましょう。", "reading": "そうしましょう。", "meaning": "Let's do it."},
    {"word": "そうじ", "reading": "そうじ", "meaning": "cleaning"},
    {"word": "掃除", "reading": "そうじ (する)", "meaning": "cleaning, sweeping"},
    {"word": "そうじします", "reading": "そうじします", "meaning": "clean"},
    {"word": "そうです。", "reading": "そうです。", "meaning": "That's right."},
    {"word": "そうですか。", "reading": "そうですか。", "meaning": "I see."},
    {"word": "そうですね。", "reading": "そうですね。", "meaning": "Oh right., Well ..."},
    {"word": "そこ", "reading": "そこ", "meaning": "that place, there; bottom, sole"},
    {"word": "そして", "reading": "そして", "meaning": "and, then"},
    {"word": "そちら", "reading": "そちら", "meaning": "over there"},
    {"word": "そっち", "reading": "そっち", "meaning": "over there"},
    {"word": "外", "reading": "そと", "meaning": "outside, exterior"},
    {"word": "その", "reading": "その", "meaning": "that"},
    {"word": "そば", "reading": "そば", "meaning": "near, close, beside; Japanese traditional buckwheat noodle"},
    {"word": "空", "reading": "そら", "meaning": "sky"},
    {"word": "それ", "reading": "それ", "meaning": "that one"},
    {"word": "それから", "reading": "それから", "meaning": "and then, after that"},
    {"word": "それでは", "reading": "それでは", "meaning": "in that situation, well then..."},
    {"word": "大使館", "reading": "たいしかん", "meaning": "embassy"},
    {"word": "大切", "reading": "たいせつ", "meaning": "important"},
    {"word": "たいてい", "reading": "たいてい", "meaning": "mostly, usually"},
    {"word": "大変", "reading": "たいへん", "meaning": "very; difficult, hard"},
    {"word": "高い", "reading": "たかい", "meaning": "tall, high; expensive"},
    {"word": "沢山", "reading": "たくさん", "meaning": "many, much"},
    {"word": "ただいま。", "reading": "ただいま。", "meaning": "I'm home., I'm back."},
    {"word": "ただしい", "reading": "ただしい", "meaning": "correct [i-adj.]"},
    {"word": "立ちます", "reading": "たちます", "meaning": "stand up"},
    {"word": "立つ", "reading": "たつ", "meaning": "to stand up"},
    {"word": "たて", "reading": "たて", "meaning": "length, height"},
    {"word": "建物", "reading": "たてもの", "meaning": "building"},
    {"word": "楽しい", "reading": "たのしい", "meaning": "enjoyable, fun"},
    {"word": "たのみます", "reading": "たのみます", "meaning": "ask, request"},
    {"word": "頼む", "reading": "たのむ", "meaning": "to request, to ask (a favor)"},
    {"word": "たばこ", "reading": "たばこ", "meaning": "tobacco, cigarettes"},
    {"word": "多分", "reading": "たぶん", "meaning": "perhaps, probably, maybe"},
    {"word": "食べ物", "reading": "たべもの", "meaning": "food"},
    {"word": "食べる", "reading": "たべる", "meaning": "to eat"},
    {"word": "卵", "reading": "たまご", "meaning": "egg"},
    {"word": "誕生日", "reading": "たんじょうび", "meaning": "birthday"},
    {"word": "大学", "reading": "だいがく", "meaning": "college; university"},
    {"word": "大丈夫", "reading": "だいじょうぶ", "meaning": "It's ok (all right); No need to worry; Everything is under control"},
    {"word": "大好き", "reading": "だいすき", "meaning": "very like-able, like very much"},
    {"word": "だいたい", "reading": "だいたい", "meaning": "almost"},
    {"word": "台所", "reading": "だいどころ", "meaning": "kitchen"},
    {"word": "だから", "reading": "だから", "meaning": "so, therefore"},
    {"word": "出します", "reading": "だします", "meaning": "take out"},
    {"word": "出す", "reading": "だす", "meaning": "to take (something) out; to hand in (something)"},
    {"word": "誰", "reading": "だれ", "meaning": "who"},
    {"word": "誰か", "reading": "だれか", "meaning": "someone"},
    {"word": "段々", "reading": "だんだん", "meaning": "gradually, by degrees"},
    {"word": "小さい", "reading": "ちいさい", "meaning": "small, little"},
    {"word": "小さな", "reading": "ちいさな", "meaning": "small, little"},
    {"word": "小さな", "reading": "ちいさな+[noun]", "meaning": "small 小さな+[noun]"},
    {"word": "近い", "reading": "ちかい", "meaning": "near, close by, short"},
    {"word": "近く", "reading": "ちかく", "meaning": "nearby; in the neighborhood"},
    {"word": "地下鉄", "reading": "ちかてつ", "meaning": "underground train, subway"},
    {"word": "ちがいます", "reading": "ちがいます", "meaning": "be different, differ"},
    {"word": "違う", "reading": "ちがう", "meaning": "to be different; to differ; wrong"},
    {"word": "地図", "reading": "ちず", "meaning": "a map"},
    {"word": "父", "reading": "ちち", "meaning": "(my) father"},
    {"word": "茶色", "reading": "ちゃいろ", "meaning": "brown"},
    {"word": "茶碗", "reading": "ちゃわん", "meaning": "rice bowl"},
    {"word": "丁度", "reading": "ちょうど", "meaning": "just, right, exactly"},
    {"word": "ちょっと", "reading": "ちょっと", "meaning": "a little, somewhat; just a little, somewhat"},
    {"word": "一日", "reading": "ついたち", "meaning": "one day; first day of the month"},
    {"word": "つかいます", "reading": "つかいます", "meaning": "use"},
    {"word": "使う", "reading": "つかう", "meaning": "to use"},
    {"word": "疲れる", "reading": "つかれる", "meaning": "to get (become) tired; to become fatigued"},
    {"word": "つきます", "reading": "つきます", "meaning": "arrive"},
    {"word": "次", "reading": "つぎ", "meaning": "next"},
    {"word": "着く", "reading": "つく", "meaning": "to arrive at, to reach"},
    {"word": "机", "reading": "つくえ", "meaning": "desk"},
    {"word": "つくりかた", "reading": "つくりかた", "meaning": "how to make"},
    {"word": "つくります", "reading": "つくります", "meaning": "make"},
    {"word": "作る", "reading": "つくる", "meaning": "to make, to create"},
    {"word": "つける", "reading": "つける", "meaning": "to turn on (e.g., a light); to take"},
    {"word": "勤める", "reading": "つとめる", "meaning": "to work (for)"},
    {"word": "つまらない", "reading": "つまらない", "meaning": "boring, dull; insignificant"},
    {"word": "冷たい", "reading": "つめたい", "meaning": "cold (things, people)"},
    {"word": "強い", "reading": "つよい", "meaning": "strong, powerful"},
    {"word": "手", "reading": "て", "meaning": "hand"},
    {"word": "手紙", "reading": "てがみ", "meaning": "letter"},
    {"word": "天気", "reading": "てんき", "meaning": "weather"},
    {"word": "出かける", "reading": "でかける", "meaning": "to go out; to depart"},
    {"word": "できる", "reading": "できる", "meaning": "to be able to (to accomplish)"},
    {"word": "出口", "reading": "でぐち", "meaning": "an exit"},
    {"word": "では", "reading": "では", "meaning": "then, well, so"},
    {"word": "では、また。", "reading": "では、また。", "meaning": "Well then, see you again."},
    {"word": "でも", "reading": "でも", "meaning": "but, however"},
    {"word": "出る", "reading": "でる", "meaning": "to appear, to leave"},
    {"word": "電気", "reading": "でんき", "meaning": "electricity, (electric) light"},
    {"word": "電車", "reading": "でんしゃ", "meaning": "electric train"},
    {"word": "電話", "reading": "でんわ", "meaning": "a telephone"},
    {"word": "電話します", "reading": "でんわします", "meaning": "call, ring"},
    {"word": "電話ばんごう", "reading": "でんわばんごう", "meaning": "telephone number"},
    {"word": "戸", "reading": "と", "meaning": "door (Japanese style)"},
    {"word": "とうきょう", "reading": "とうきょう", "meaning": "Tokyo"},
    {"word": "とうふ", "reading": "とうふ", "meaning": "tofu"},
    {"word": "十", "reading": "とお", "meaning": "ten"},
    {"word": "遠い", "reading": "とおい", "meaning": "far (away), distant"},
    {"word": "十日", "reading": "とおか", "meaning": "ten days; tenth day of the month"},
    {"word": "とおく", "reading": "とおく", "meaning": "distantly, far [noun]"},
    {"word": "時々", "reading": "ときどき", "meaning": "sometimes"},
    {"word": "時計", "reading": "とけい", "meaning": "a watch; a clock"},
    {"word": "所", "reading": "ところ", "meaning": "place"},
    {"word": "年", "reading": "とし", "meaning": "year, age"},
    {"word": "図書館", "reading": "としょかん", "meaning": "library"},
    {"word": "とても", "reading": "とても", "meaning": "very (much), greatly, exceedingly"},
    {"word": "隣", "reading": "となり", "meaning": "next to, next door to"},
    {"word": "とびます", "reading": "とびます", "meaning": "fly"},
    {"word": "飛ぶ", "reading": "とぶ", "meaning": "to fly, to hop"},
    {"word": "とまります", "reading": "とまります", "meaning": "stop"},
    {"word": "止まる", "reading": "とまる", "meaning": "to come to a halt"},
    {"word": "友達", "reading": "ともだち", "meaning": "friend"},
    {"word": "鳥", "reading": "とり", "meaning": "chicken (lit., bird)"},
    {"word": "鶏肉", "reading": "とりにく", "meaning": "chicken meat"},
    {"word": "とります", "reading": "とります", "meaning": "take"},
    {"word": "取る", "reading": "とる", "meaning": "to take (a class); to get (a grade)"},
    {"word": "どう", "reading": "どう", "meaning": "how, in what way"},
    {"word": "どういたしまして。", "reading": "どういたしまして。", "meaning": "You are welcome., Not at all."},
    {"word": "どうして", "reading": "どうして", "meaning": "why, for what reason"},
    {"word": "どうぞ", "reading": "どうぞ", "meaning": "please, kindly, by all means"},
    {"word": "どうぞ。", "reading": "どうぞ。", "meaning": "Please."},
    {"word": "動物", "reading": "どうぶつ", "meaning": "animal"},
    {"word": "どうも", "reading": "どうも", "meaning": "Thank you; somehow; no matter how hard one may try"},
    {"word": "どうも。", "reading": "どうも。", "meaning": "Thanks."},
    {"word": "どうもありがとう。", "reading": "どうもありがとう。", "meaning": "Thanks a lot."},
    {"word": "どこ", "reading": "どこ", "meaning": "where, what place"},
    {"word": "どこか", "reading": "どこか", "meaning": "somewhere"},
    {"word": "どちら", "reading": "どちら", "meaning": "which (one) (way); where (polite)"},
    {"word": "どっち", "reading": "どっち", "meaning": "which one, which way"},
    {"word": "どなた", "reading": "どなた", "meaning": "who"},
    {"word": "どの", "reading": "どの", "meaning": "which"},
    {"word": "土曜日", "reading": "どようび", "meaning": "Saturday"},
    {"word": "どれ", "reading": "どれ", "meaning": "which one"},
    {"word": "どんな", "reading": "どんな", "meaning": "what, what kind of"},
    {"word": "ない", "reading": "ない", "meaning": "there isn't, doesn't have"},
    {"word": "中", "reading": "なか", "meaning": "inside, middle, among"},
    {"word": "長い", "reading": "ながい", "meaning": "long, lengthy"},
    {"word": "なきます", "reading": "なきます", "meaning": "sing, mew, moo, etc."},
    {"word": "鳴く", "reading": "なく", "meaning": "to make sound (animal)"},
    {"word": "無くす", "reading": "なくす", "meaning": "to lose something"},
    {"word": "なぜ", "reading": "なぜ", "meaning": "why (same as どうして)"},
    {"word": "夏", "reading": "なつ", "meaning": "summer"},
    {"word": "夏休み", "reading": "なつやすみ", "meaning": "summer vacation"},
    {"word": "七つ", "reading": "ななつ", "meaning": "seven things"},
    {"word": "何", "reading": "なに", "meaning": "what"},
    {"word": "何か", "reading": "なにか", "meaning": "something"},
    {"word": "七日", "reading": "なのか", "meaning": "seven days; seventh day (of the month)"},
    {"word": "名前", "reading": "なまえ", "meaning": "name"},
    {"word": "ならいます", "reading": "ならいます", "meaning": "learn (from somebody)"},
    {"word": "習う", "reading": "ならう", "meaning": "to learn"},
    {"word": "ならびます", "reading": "ならびます", "meaning": "(someone) line up"},
    {"word": "並ぶ", "reading": "ならぶ", "meaning": "to line up, to stand in a line (v.i.)"},
    {"word": "並べる", "reading": "ならべる", "meaning": "to put (things) side by side; to line up"},
    {"word": "なります", "reading": "なります", "meaning": "become"},
    {"word": "なる", "reading": "なる", "meaning": "to become"},
    {"word": "何", "reading": "なん / なに", "meaning": "what"},
    {"word": "何", "reading": "なん; なに", "meaning": "what"},
    {"word": "何時", "reading": "なんじ", "meaning": "what time"},
    {"word": "何日", "reading": "なんにち", "meaning": "which day of the month"},
    {"word": "何～", "reading": "なん～", "meaning": "what sort of ~"},
    {"word": "二", "reading": "に", "meaning": "two"},
    {"word": "にぎやか", "reading": "にぎやか", "meaning": "bustling, busy"},
    {"word": "肉", "reading": "にく", "meaning": "meat"},
    {"word": "西", "reading": "にし", "meaning": "west"},
    {"word": "日曜日", "reading": "にちようび", "meaning": "Sunday"},
    {"word": "二年", "reading": "にねん", "meaning": "two years"},
    {"word": "日本", "reading": "にほん", "meaning": "Japan"},
    {"word": "日本語", "reading": "にほんご", "meaning": "Japanese language"},
    {"word": "荷物", "reading": "にもつ", "meaning": "luggage; baggage"},
    {"word": "庭", "reading": "にわ", "meaning": "garden"},
    {"word": "ぬぎます", "reading": "ぬぎます", "meaning": "take off"},
    {"word": "脱ぐ", "reading": "ぬぐ", "meaning": "to take off (clothes)"},
    {"word": "ぬります", "reading": "ぬります", "meaning": "paint"},
    {"word": "温い", "reading": "ぬるい", "meaning": "lukewarm"},
    {"word": "猫", "reading": "ねこ", "meaning": "cat"},
    {"word": "寝る", "reading": "ねる", "meaning": "to sleep; to go to sleep; to go to bed"},
    {"word": "のぼります", "reading": "のぼります", "meaning": "go up, climb"},
    {"word": "登る", "reading": "のぼる", "meaning": "to climb"},
    {"word": "飲みます", "reading": "のみます", "meaning": "drink"},
    {"word": "飲み物", "reading": "のみもの", "meaning": "drink, beverage"},
    {"word": "飲む", "reading": "のむ", "meaning": "to drink"},
    {"word": "のります", "reading": "のります", "meaning": "get on, ride, take"},
    {"word": "乗る", "reading": "のる", "meaning": "to get on, to ride in, to board"},
    {"word": "歯", "reading": "は", "meaning": "tooth"},
    {"word": "はい", "reading": "はい", "meaning": "yes"},
    {"word": "はい。", "reading": "はい。", "meaning": "Yes."},
    {"word": "灰皿", "reading": "はいざら", "meaning": "ashtray"},
    {"word": "入ります", "reading": "はいります", "meaning": "enter"},
    {"word": "入る", "reading": "はいる", "meaning": "to enter, to contain, to hold"},
    {"word": "葉書", "reading": "はがき", "meaning": "postcard"},
    {"word": "はきます", "reading": "はきます", "meaning": "put on"},
    {"word": "はく", "reading": "はく", "meaning": "to put on (items below your waist)"},
    {"word": "箱", "reading": "はこ", "meaning": "box"},
    {"word": "橋", "reading": "はし", "meaning": "bridge"},
    {"word": "はし/おはし", "reading": "はし/おはし", "meaning": "chopsticks"},
    {"word": "走る", "reading": "はしる", "meaning": "to run"},
    {"word": "はじまります", "reading": "はじまります", "meaning": "begin, start"},
    {"word": "始まる", "reading": "はじまる", "meaning": "(something) begins"},
    {"word": "初め; 始め", "reading": "はじめ", "meaning": "beginning, start"},
    {"word": "初めて", "reading": "はじめて", "meaning": "for the first time"},
    {"word": "はじめに", "reading": "はじめに", "meaning": "at the beginning"},
    {"word": "はじめまして。", "reading": "はじめまして。", "meaning": "Nice to see you."},
    {"word": "二十歳", "reading": "はたち", "meaning": "20 years old"},
    {"word": "はたらきます", "reading": "はたらきます", "meaning": "work"},
    {"word": "働く", "reading": "はたらく", "meaning": "to work"},
    {"word": "八", "reading": "はち", "meaning": "eight"},
    {"word": "二十日", "reading": "はつか", "meaning": "twenty days, twentieth (day of the month)"},
    {"word": "花", "reading": "はな", "meaning": "flower"},
    {"word": "話", "reading": "はなし", "meaning": "talk (chat), story"},
    {"word": "話します", "reading": "はなします", "meaning": "speak, talk, tell"},
    {"word": "話す", "reading": "はなす", "meaning": "to speak"},
    {"word": "母", "reading": "はは", "meaning": "(my) mother"},
    {"word": "早い", "reading": "はやい", "meaning": "early"},
    {"word": "はります", "reading": "はります", "meaning": "stick, put something on"},
    {"word": "春", "reading": "はる", "meaning": "spring"},
    {"word": "晴れ", "reading": "はれ", "meaning": "clear (sunny) weather"},
    {"word": "晴れる", "reading": "はれる", "meaning": "to be sunny"},
    {"word": "半", "reading": "はん", "meaning": "half (e.g., にじはん | half-past two)"},
    {"word": "半分", "reading": "はんぶん", "meaning": "half"},
    {"word": "晩", "reading": "ばん", "meaning": "evening"},
    {"word": "番号", "reading": "ばんごう", "meaning": "number, series of digits"},
    {"word": "晩御飯", "reading": "ばんごはん", "meaning": "dinner, evening meal"},
    {"word": "日", "reading": "ひ", "meaning": "day"},
    {"word": "東", "reading": "ひがし", "meaning": "east"},
    {"word": "ひきます", "reading": "ひきます", "meaning": "pull"},
    {"word": "引く", "reading": "ひく", "meaning": "to pull, to draw; subtract"},
    {"word": "低い", "reading": "ひくい", "meaning": "short, low"},
    {"word": "飛行機", "reading": "ひこうき", "meaning": "airplane"},
    {"word": "左", "reading": "ひだり", "meaning": "left hand side"},
    {"word": "人", "reading": "ひと", "meaning": "man, person"},
    {"word": "一つ", "reading": "ひとつ", "meaning": "one thing"},
    {"word": "一月", "reading": "ひとつき", "meaning": "one month"},
    {"word": "一人", "reading": "ひとり", "meaning": "one person"},
    {"word": "暇", "reading": "ひま", "meaning": "free time, leisure"},
    {"word": "百", "reading": "ひゃく", "meaning": "hundred"},
    {"word": "平仮名", "reading": "ひらがな", "meaning": "hiragana"},
    {"word": "昼", "reading": "ひる", "meaning": "noon, daytime"},
    {"word": "昼御飯", "reading": "ひるごはん", "meaning": "lunch, midday meal"},
    {"word": "広い", "reading": "ひろい", "meaning": "spacious; wide; broad"},
    {"word": "病院", "reading": "びょういん", "meaning": "hospital"},
    {"word": "病気", "reading": "びょうき", "meaning": "illness; sickness"},
    {"word": "封筒", "reading": "ふうとう", "meaning": "envelope"},
    {"word": "ふきます", "reading": "ふきます", "meaning": "blow"},
    {"word": "吹く", "reading": "ふく", "meaning": "to blow (wind, etc.)"},
    {"word": "二つ", "reading": "ふたつ", "meaning": "two things"},
    {"word": "二人", "reading": "ふたり", "meaning": "two people"},
    {"word": "二日", "reading": "ふつか", "meaning": "two days; second day of the month"},
    {"word": "太い", "reading": "ふとい", "meaning": "fat, thick"},
    {"word": "冬", "reading": "ふゆ", "meaning": "winter"},
    {"word": "ふります", "reading": "ふります", "meaning": "fall, come down"},
    {"word": "降る", "reading": "ふる", "meaning": "to precipitate, to fall (e.g., rain, snow, etc.)"},
    {"word": "古い", "reading": "ふるい", "meaning": "old (in reference to objects, not people), aged, ancient"},
    {"word": "ふろ", "reading": "ふろ", "meaning": "bath    「おふろ」more polite"},
    {"word": "豚肉", "reading": "ぶたにく", "meaning": "pork"},
    {"word": "文", "reading": "ぶん", "meaning": "sentence"},
    {"word": "文章", "reading": "ぶんしょう", "meaning": "sentence, text"},
    {"word": "下手", "reading": "へた", "meaning": "unskillful, poor"},
    {"word": "部屋", "reading": "へや", "meaning": "a room"},
    {"word": "辺", "reading": "へん", "meaning": "area, vicinity"},
    {"word": "勉強", "reading": "べんきょう (する)", "meaning": "study"},
    {"word": "べんきょうします", "reading": "べんきょうします", "meaning": "study"},
    {"word": "便利", "reading": "べんり", "meaning": "convenient, handy"},
    {"word": "ほう", "reading": "ほう", "meaning": "ＡよりＢのほうが～。B is ... than A."},
    {"word": "外", "reading": "ほか", "meaning": "other, the rest"},
    {"word": "欲しい", "reading": "ほしい", "meaning": "to want, in need of"},
    {"word": "細い", "reading": "ほそい", "meaning": "thin, slender, fine"},
    {"word": "本", "reading": "ほん", "meaning": "book"},
    {"word": "本棚", "reading": "ほんだな", "meaning": "bookshelf"},
    {"word": "本当", "reading": "ほんとう", "meaning": "real, true"},
    {"word": "ほんや", "reading": "ほんや", "meaning": "bookshop"},
    {"word": "帽子", "reading": "ぼうし", "meaning": "hat; cap"},
    {"word": "ぼく", "reading": "ぼく", "meaning": "I (generally young boys, but some adult use as a style)"},
    {"word": "毎朝", "reading": "まいあさ", "meaning": "every morning"},
    {"word": "毎月", "reading": "まいげつ / まいつき", "meaning": "every month"},
    {"word": "毎月", "reading": "まいげつ; まいつき", "meaning": "every month, monthly"},
    {"word": "毎週", "reading": "まいしゅう", "meaning": "every week"},
    {"word": "毎日", "reading": "まいにち", "meaning": "every day"},
    {"word": "毎年", "reading": "まいねん / まいとし", "meaning": "every year"},
    {"word": "毎年", "reading": "まいねん; まいとし", "meaning": "every year, yearly, annually"},
    {"word": "毎晩", "reading": "まいばん", "meaning": "every night"},
    {"word": "前", "reading": "まえ", "meaning": "before, in front"},
    {"word": "まがります", "reading": "まがります", "meaning": "turn"},
    {"word": "曲る", "reading": "まがる", "meaning": "to turn, to bend"},
    {"word": "まずい", "reading": "まずい", "meaning": "terrible (in reference to food), unappetizing, unpleasant (taste)"},
    {"word": "また", "reading": "また", "meaning": "and; furthermore"},
    {"word": "まだ", "reading": "まだ", "meaning": "yet, still, besides"},
    {"word": "町", "reading": "まち", "meaning": "town; city"},
    {"word": "まちます", "reading": "まちます", "meaning": "wait"},
    {"word": "まっすぐ", "reading": "まっすぐ", "meaning": "straight (ahead), direct"},
    {"word": "待つ", "reading": "まつ", "meaning": "to wait"},
    {"word": "窓", "reading": "まど", "meaning": "window"},
    {"word": "丸い; 円い", "reading": "まるい", "meaning": "round, circular"},
    {"word": "万", "reading": "まん", "meaning": "ten thousand"},
    {"word": "万年筆", "reading": "まんねんひつ", "meaning": "fountain pen"},
    {"word": "みがきます", "reading": "みがきます", "meaning": "polish, brush"},
    {"word": "磨く", "reading": "みがく", "meaning": "to brush (teeth); to polish"},
    {"word": "右", "reading": "みぎ", "meaning": "right hand side"},
    {"word": "短い", "reading": "みじかい", "meaning": "short (length)"},
    {"word": "水", "reading": "みず", "meaning": "water"},
    {"word": "店", "reading": "みせ", "meaning": "store, shop"},
    {"word": "見せる", "reading": "みせる", "meaning": "to show, to display"},
    {"word": "道", "reading": "みち", "meaning": "road, street; way, directions"},
    {"word": "三日", "reading": "みっか", "meaning": "three days, third day of the month"},
    {"word": "三つ", "reading": "みっつ", "meaning": "three things"},
    {"word": "緑", "reading": "みどり", "meaning": "green"},
    {"word": "皆さん", "reading": "みなさん", "meaning": "all of you, everyone"},
    {"word": "南", "reading": "みなみ", "meaning": "South"},
    {"word": "耳", "reading": "みみ", "meaning": "ear"},
    {"word": "見る", "reading": "みる", "meaning": "to see, to look"},
    {"word": "みんな", "reading": "みんな", "meaning": "all, everyone, everybody"},
    {"word": "六日", "reading": "むいか", "meaning": "six days; sixth day of month"},
    {"word": "向こう", "reading": "むこう", "meaning": "beyond, over there"},
    {"word": "難しい", "reading": "むずかしい", "meaning": "difficult"},
    {"word": "六つ", "reading": "むっつ", "meaning": "six things"},
    {"word": "村", "reading": "むら", "meaning": "village"},
    {"word": "目", "reading": "め", "meaning": "eye(s)"},
    {"word": "眼鏡", "reading": "めがね", "meaning": "eye glasses"},
    {"word": "もう", "reading": "もう", "meaning": "already; again; more"},
    {"word": "もう一度", "reading": "もういちど", "meaning": "again"},
    {"word": "木", "reading": "もく", "meaning": "Thursday = もくようび。"},
    {"word": "木曜日", "reading": "もくようび", "meaning": "Thursday"},
    {"word": "もしもし", "reading": "もしもし", "meaning": "Hello? (used on the phone)"},
    {"word": "もちます", "reading": "もちます", "meaning": "have, hold, carry"},
    {"word": "もちろん", "reading": "もちろん", "meaning": "of course"},
    {"word": "もっていきます", "reading": "もっていきます", "meaning": "take (something) （もってきます。= bring (something)）"},
    {"word": "もっと", "reading": "もっと", "meaning": "more"},
    {"word": "持つ", "reading": "もつ", "meaning": "to hold, to carry; to possess"},
    {"word": "物", "reading": "もの", "meaning": "thing (concrete object)"},
    {"word": "もらいます", "reading": "もらいます", "meaning": "receive"},
    {"word": "門", "reading": "もん", "meaning": "gate"},
    {"word": "問題", "reading": "もんだい", "meaning": "a problem"},
    {"word": "もんだいようし", "reading": "もんだいようし", "meaning": "question sheet"},
    {"word": "もんだいれい", "reading": "もんだいれい", "meaning": "sample question"},
    {"word": "八百屋", "reading": "やおや", "meaning": "greengrocer"},
    {"word": "野菜", "reading": "やさい", "meaning": "vegetable"},
    {"word": "易しい", "reading": "やさしい", "meaning": "easy, plain, simple"},
    {"word": "やじるし", "reading": "やじるし", "meaning": "arrow"},
    {"word": "安い", "reading": "やすい", "meaning": "inexpensive; cheap (things)"},
    {"word": "休み", "reading": "やすみ", "meaning": "holiday; day off; absence"},
    {"word": "休みます", "reading": "やすみます", "meaning": "have a day off, rest, be absent"},
    {"word": "休む", "reading": "やすむ", "meaning": "to rest, to have a break, to get time off"},
    {"word": "八つ", "reading": "やっつ", "meaning": "eight things"},
    {"word": "山", "reading": "やま", "meaning": "mountain"},
    {"word": "やります", "reading": "やります", "meaning": "do"},
    {"word": "やる", "reading": "やる", "meaning": "to do; to give (to pets, parents, siblings, etc.)"},
    {"word": "夕方", "reading": "ゆうがた", "meaning": "late afternoon (typically just before dinner time), evening"},
    {"word": "夕飯", "reading": "ゆうはん", "meaning": "dinner, supper, evening meal"},
    {"word": "郵便局", "reading": "ゆうびんきょく", "meaning": "post office"},
    {"word": "昨夜", "reading": "ゆうべ", "meaning": "last night"},
    {"word": "有名", "reading": "ゆうめい", "meaning": "famous"},
    {"word": "雪", "reading": "ゆき", "meaning": "snow"},
    {"word": "ゆっくりと", "reading": "ゆっくりと", "meaning": "slowly, at ease"},
    {"word": "八日", "reading": "ようか", "meaning": "eight days; eighth day of the month"},
    {"word": "洋服", "reading": "ようふく", "meaning": "Western-style clothes"},
    {"word": "よく", "reading": "よく", "meaning": "frequently, often (much); well, skillfully"},
    {"word": "横", "reading": "よこ", "meaning": "beside; side; width"},
    {"word": "四日", "reading": "よっか", "meaning": "four days; fourth day of the month"},
    {"word": "四つ", "reading": "よっつ", "meaning": "four things"},
    {"word": "よびます", "reading": "よびます", "meaning": "call, invite"},
    {"word": "呼ぶ", "reading": "よぶ", "meaning": "to call (one's name); to invite"},
    {"word": "読みます", "reading": "よみます", "meaning": "read"},
    {"word": "読む", "reading": "よむ", "meaning": "to read"},
    {"word": "夜", "reading": "よる", "meaning": "evening, night"},
    {"word": "よろしく。", "reading": "よろしく。", "meaning": "(Please favor me.)"},
    {"word": "弱い", "reading": "よわい", "meaning": "weak"},
    {"word": "来月", "reading": "らいげつ", "meaning": "next month"},
    {"word": "来週", "reading": "らいしゅう", "meaning": "next week"},
    {"word": "来年", "reading": "らいねん", "meaning": "next year"},
    {"word": "りっぱ", "reading": "りっぱ", "meaning": "splendid, fine"},
    {"word": "留学生", "reading": "りゅうがくせい", "meaning": "international student"},
    {"word": "両親", "reading": "りょうしん", "meaning": "parents (lit., both parents)"},
    {"word": "料理", "reading": "りょうり", "meaning": "cooking; cuisine"},
    {"word": "旅行", "reading": "りょこう", "meaning": "travel, trip"},
    {"word": "りょこうがいしゃ", "reading": "りょこうがいしゃ", "meaning": "travel agency"},
    {"word": "りょこうします", "reading": "りょこうします", "meaning": "travel"},
    {"word": "りんご", "reading": "りんご", "meaning": "apple"},
    {"word": "零", "reading": "れい", "meaning": "zero, nought"},
    {"word": "冷蔵庫", "reading": "れいぞうこ", "meaning": "refrigerator"},
    {"word": "れんしゅう", "reading": "れんしゅう", "meaning": "practice"},
    {"word": "練習", "reading": "れんしゅう (する)", "meaning": "(to) practice"},
    {"word": "れんしゅうします", "reading": "れんしゅうします", "meaning": "practice"},
    {"word": "廊下", "reading": "ろうか", "meaning": "corridor"},
    {"word": "六", "reading": "ろく", "meaning": "six"},
    {"word": "六本", "reading": "ろっぽん", "meaning": "six (long objects)"},
    {"word": "若い", "reading": "わかい", "meaning": "young"},
    {"word": "わかります", "reading": "わかります", "meaning": "understand, know"},
    {"word": "分かる", "reading": "わかる", "meaning": "to understand"},
    {"word": "忘れる", "reading": "わすれる", "meaning": "to forget"},
    {"word": "私", "reading": "わたくし", "meaning": "I (formal), myself, private affairs"},
    {"word": "私", "reading": "わたし", "meaning": "I, myself"},
    {"word": "わたします", "reading": "わたします", "meaning": "hand over"},
    {"word": "渡す", "reading": "わたす", "meaning": "to hand (something) over (v.t.); to get across"},
    {"word": "わたります", "reading": "わたります", "meaning": "cross"},
    {"word": "渡る", "reading": "わたる", "meaning": "to cross over, to go across"},
    {"word": "悪い", "reading": "わるい", "meaning": "bad, sinful; inferior"},
    {"word": "アパート", "reading": "アパート", "meaning": "apartment (abbr.)"},
    {"word": "アメリカ", "reading": "アメリカ", "meaning": "The United States of America"},
    {"word": "エアコン", "reading": "エアコン", "meaning": "air conditioner"},
    {"word": "エレベーター", "reading": "エレベーター", "meaning": "elevator"},
    {"word": "カタカナ", "reading": "カタカナ", "meaning": "katakana"},
    {"word": "カップ", "reading": "カップ", "meaning": "cup"},
    {"word": "カメラ", "reading": "カメラ", "meaning": "camera"},
    {"word": "カレンダー", "reading": "カレンダー", "meaning": "calendar"},
    {"word": "カレー", "reading": "カレー", "meaning": "curry (abbr. for curry and rice)"},
    {"word": "キロ; キログラム", "reading": "キロ; キログラム", "meaning": "(abbr.) kilo (kilogram)"},
    {"word": "キロ; キロメートル", "reading": "キロ; キロメートル", "meaning": "(abbr.) kilo (kilometer)"},
    {"word": "ギター", "reading": "ギター", "meaning": "guitar"},
    {"word": "クラス", "reading": "クラス", "meaning": "a class"},
    {"word": "グラム", "reading": "グラム", "meaning": "gram"},
    {"word": "ケーキ", "reading": "ケーキ", "meaning": "cake"},
    {"word": "コップ", "reading": "コップ", "meaning": "a tumbler; a glass"},
    {"word": "コピー", "reading": "コピー", "meaning": "copy"},
    {"word": "コピーします", "reading": "コピーします", "meaning": "make a copy"},
    {"word": "コピーする", "reading": "コピーする", "meaning": "to copy"},
    {"word": "コート", "reading": "コート", "meaning": "coat; court (e.g., tennis)"},
    {"word": "コーヒー", "reading": "コーヒー", "meaning": "coffee"},
    {"word": "サッカー", "reading": "サッカー", "meaning": "soccer, football"},
    {"word": "シャツ", "reading": "シャツ", "meaning": "shirt"},
    {"word": "シャワー", "reading": "シャワー", "meaning": "shower"},
    {"word": "ジュース", "reading": "ジュース", "meaning": "juice"},
    {"word": "スカート", "reading": "スカート", "meaning": "skirt"},
    {"word": "ストーブ", "reading": "ストーブ", "meaning": "heater (lit: stove)"},
    {"word": "スプーン", "reading": "スプーン", "meaning": "spoon"},
    {"word": "スポーツ", "reading": "スポーツ", "meaning": "sport(s)"},
    {"word": "スリッパ", "reading": "スリッパ", "meaning": "slippers"},
    {"word": "ズボン", "reading": "ズボン", "meaning": "trousers"},
    {"word": "セーター", "reading": "セーター", "meaning": "sweater"},
    {"word": "ゼロ", "reading": "ゼロ", "meaning": "zero"},
    {"word": "タクシー", "reading": "タクシー", "meaning": "taxi"},
    {"word": "ティッシュペーパー", "reading": "ティッシュペーパー", "meaning": "tissue"},
    {"word": "テスト", "reading": "テスト", "meaning": "test"},
    {"word": "テレビ", "reading": "テレビ", "meaning": "television, TV"},
    {"word": "テーブル", "reading": "テーブル", "meaning": "table"},
    {"word": "テープ", "reading": "テープ", "meaning": "tape"},
    {"word": "テープレコーダー", "reading": "テープレコーダー", "meaning": "tape recorder"},
    {"word": "デパート", "reading": "デパート", "meaning": "(abbr.) department store"},
    {"word": "トイレ", "reading": "トイレ", "meaning": "bathroom; toilet"},
    {"word": "トイレットペーパー", "reading": "トイレットペーパー", "meaning": "toilet paper"},
    {"word": "ドア", "reading": "ドア", "meaning": "door (Western style)"},
    {"word": "ナイフ", "reading": "ナイフ", "meaning": "knife"},
    {"word": "ニュース", "reading": "ニュース", "meaning": "news"},
    {"word": "ネクタイ", "reading": "ネクタイ", "meaning": "tie, necktie"},
    {"word": "ノート", "reading": "ノート", "meaning": "notebook"},
    {"word": "ハンカチ", "reading": "ハンカチ", "meaning": "handkerchief"},
    {"word": "バス", "reading": "バス", "meaning": "bus; bath; bass"},
    {"word": "バス会社", "reading": "バスがいしゃ", "meaning": "bus agency, bus company"},
    {"word": "バスてい", "reading": "バスてい", "meaning": "bus stop"},
    {"word": "バスりょこう", "reading": "バスりょこう", "meaning": "bus tour, bus trip"},
    {"word": "バター", "reading": "バター", "meaning": "butter"},
    {"word": "パン", "reading": "パン", "meaning": "bread"},
    {"word": "パンや", "reading": "パンや", "meaning": "bakery"},
    {"word": "パーティー", "reading": "パーティー", "meaning": "a party"},
    {"word": "ビル", "reading": "ビル", "meaning": "building"},
    {"word": "フィルム", "reading": "フィルム", "meaning": "film (roll of)"},
    {"word": "フォーク", "reading": "フォーク", "meaning": "fork"},
    {"word": "プール", "reading": "プール", "meaning": "swimming pool"},
    {"word": "ベッド", "reading": "ベッド", "meaning": "bed"},
    {"word": "ペット", "reading": "ペット", "meaning": "pet"},
    {"word": "ペン", "reading": "ペン", "meaning": "pen"},
    {"word": "ページ", "reading": "ページ", "meaning": "a page"},
    {"word": "ホテル", "reading": "ホテル", "meaning": "hotel"},
    {"word": "ボタン", "reading": "ボタン", "meaning": "button"},
    {"word": "ボールペン", "reading": "ボールペン", "meaning": "ball-point pen"},
    {"word": "ポケット", "reading": "ポケット", "meaning": "pocket"},
    {"word": "ポスト", "reading": "ポスト", "meaning": "mailbox; post, position"},
    {"word": "マッチ", "reading": "マッチ", "meaning": "match"},
    {"word": "メモ", "reading": "メモ", "meaning": "memo"},
    {"word": "メモします", "reading": "メモします", "meaning": "make a note"},
    {"word": "メートル", "reading": "メートル", "meaning": "meter"},
    {"word": "ラジオ", "reading": "ラジオ", "meaning": "radio"},
    {"word": "ラジオカセ", "reading": "ラジオカセ", "meaning": "radio cassette player"},
    {"word": "ラーメン", "reading": "ラーメン", "meaning": "ramen, noodle"},
    {"word": "レコード", "reading": "レコード", "meaning": "record"},
    {"word": "レストラン", "reading": "レストラン", "meaning": "restaurant"},
    {"word": "ワイシャツ", "reading": "ワイシャツ", "meaning": "shirt (lit: white shirt), business shirt"},
    {"word": "ワイシャツ\\n(Yシャツ)", "reading": "ワイシャツ", "meaning": "business shirt (white shirt)"},
    {"word": "～円", "reading": "～えん", "meaning": "Yen"},
    {"word": "～回", "reading": "～かい", "meaning": "counter for occurrences (~ times)"},
    {"word": "～日間", "reading": "～かかん", "meaning": "for ... day(s)"},
    {"word": "～か月", "reading": "～かげつ", "meaning": "(number of) months"},
    {"word": "～月", "reading": "～がつ", "meaning": "month of year"},
    {"word": "～がります", "reading": "～がります", "meaning": "(third person) wants to ...  [「〜たい」のstem]＋[てform of がります]＋ います"},
    {"word": "～がる", "reading": "～がる", "meaning": "feel"},
    {"word": "～側", "reading": "～がわ", "meaning": "~ side"},
    {"word": "～くらい/ぐらい", "reading": "～くらい/ぐらい", "meaning": "about ..."},
    {"word": "～くらい; ぐらい", "reading": "～くらい; ぐらい", "meaning": "approximate (quantity)"},
    {"word": "～個", "reading": "～こ", "meaning": "counter for small items (e.g., fruits, cups)"},
    {"word": "～ころ; ～ごろ", "reading": "～ころ; ～ごろ", "meaning": "about, toward, approximately (time)"},
    {"word": "～ごろ", "reading": "～ごろ", "meaning": "around ... (for time)"},
    {"word": "～歳", "reading": "～さい", "meaning": "~ years old"},
    {"word": "～冊", "reading": "～さつ", "meaning": "counter for books"},
    {"word": "～さん", "reading": "～さん", "meaning": "Mr. ~, Ms. ~"},
    {"word": "～週間", "reading": "～しゅうかん", "meaning": "~ weeks"},
    {"word": "～時", "reading": "～じ", "meaning": "~ o'clock (time)"},
    {"word": "～人", "reading": "～じん", "meaning": "counter for people"},
    {"word": "～すぎ", "reading": "～すぎ", "meaning": "past; to exceed, ~ too much"},
    {"word": "～ずつ", "reading": "～ずつ", "meaning": "at a time"},
    {"word": "～たち", "reading": "～たち", "meaning": "plural suffix"},
    {"word": "～台", "reading": "～だい", "meaning": "counter for vehicles; machines"},
    {"word": "～だけ", "reading": "～だけ", "meaning": "only ~, just ~, as ~"},
    {"word": "～中", "reading": "～ちゅう", "meaning": "during, while ~ing"},
    {"word": "～つ", "reading": "～つ", "meaning": "counter for object"},
    {"word": "～時", "reading": "～とき", "meaning": "at the time of ~"},
    {"word": "～度", "reading": "～ど", "meaning": "counter for occurrences; ~ degree; ~ point"},
    {"word": "～など", "reading": "～など", "meaning": "et cetera"},
    {"word": "～日", "reading": "～にち", "meaning": "~ day of the month, for ~ days"},
    {"word": "～人", "reading": "～にん", "meaning": "counter for people"},
    {"word": "～年", "reading": "～ねん", "meaning": "~ years"},
    {"word": "～はい/ばい/ぱい", "reading": "～はい/ばい/ぱい", "meaning": "cups of ..."},
    {"word": "～匹", "reading": "～ひき", "meaning": "counter for small animals"},
    {"word": "～ひき/びき/ぴき", "reading": "～ひき/びき/ぴき", "meaning": "counter for animal"},
    {"word": "～分", "reading": "～ふん", "meaning": "~ minutes"},
    {"word": "～分", "reading": "～ふん/ぷん", "meaning": "minute(s)"},
    {"word": "～本", "reading": "～ほん/ぼん/ぽん", "meaning": "counter for long object"},
    {"word": "～枚", "reading": "～まい", "meaning": "counter for flat things"},
    {"word": "～屋", "reading": "～や", "meaning": "~ shop"},
    {"word": "～キロ", "reading": "～キロ", "meaning": "kg ="}
]
